fileID = fopen('dbcp_pi_4.txt','r');
x11 = fscanf(fileID,'%f');
fileID = fopen('dbcp_pia_4.txt','r');
x12 = fscanf(fileID,'%f');
fileID = fopen('dbcp_pim_4.txt','r');
x13 = fscanf(fileID,'%f');
fileID = fopen('dbcp_pii_4.txt','r');
x14 = fscanf(fileID,'%f');
fileID = fopen('dbcp_local_pi_4.txt','r');
x21 = fscanf(fileID,'%f');
fileID = fopen('dbcp_local_pia_4.txt','r');
x22 = fscanf(fileID,'%f');
fileID = fopen('dbcp_local_pim_4.txt','r');
x23 = fscanf(fileID,'%f');
fileID = fopen('dbcp_local_pii_4.txt','r');
x24 = fscanf(fileID,'%f');
%fileID = fopen('dbcp_swap_pi_4.txt','r');
%x31 = fscanf(fileID,'%f');
y = 2:size(x11);

%plot(y,x11(2:size(x11)),y,x12(2:size(x11)),y,x13(2:size(x11)),y,x14(2:size(x11)),y,x21(2:size(x11)),y,x22(2:size(x11)),y,x23(2:size(x11)),y,x24(2:size(x11)));
%plot(y,x11(2:size(x11)),y,x21(2:size(x11)),y,x31(2:size(x11)));
plot(y,x11(2:size(x11)),y,x21(2:size(x11)));
xlabel('Number of Controllers(k)');
ylabel('\pi Value');
%legend('\pi_{latency}','\pi_{avglatency}','\pi_{max_latency}','\pi_{ic}','local_\pi{latency}','local_\pi_{avglatency}','local_\pi_{max_latency}','local_\pi_{ic}');
%legend('\pi_{latency}','local-\pi_{latency}','swap-\pi_{latency}');
legend('\pi_{latency}','local-\pi_{latency}');
print('Metric Plot','-dpng');