fileID = fopen('dbcp_mypilat_6.txt','r');
x11 = fscanf(fileID,'%f');
fileID = fopen('dbcp_mypiic_6.txt','r');
x12 = fscanf(fileID,'%f');
fileID = fopen('wdbcp_mypilat_6.txt','r');
x21 = fscanf(fileID,'%f');
fileID = fopen('wdbcp_mypiic_6.txt','r');
x22 = fscanf(fileID,'%f');
fileID = fopen('ispici_mypilat_6.txt','r');
x3 = fscanf(fileID,'%f');
fileID = fopen('gspici_mypilat_6.txt','r');
x4 = fscanf(fileID,'%f');
fileID = fopen('ispici_myk_6.txt','r');
y3 = fscanf(fileID,'%f');
fileID = fopen('gspici_myk_6.txt','r');
y4 = fscanf(fileID,'%f');
x1 = x11 + x12;
x2 = x21 + x22;
y = 2:size(x2);
plot(y,x1(2:size(x1)),y,x2(2:size(x1)),y3,x3,y4,x4);
%plot(y,x2(2:size(x2)),y3,x3,y4,x4);
xlabel('Number of Controllers(k)');
ylabel('\pi Value Average');
legend('\pi^{DBCP}','\pi^{WDBCP}','\pi^{ISPICi}','\pi^{GSPICi}');
%legend('\pi^{WDBCP}','\pi^{ISPICi}','\pi^{GSPICi}');
print('our_comp_6','-dpng');