(function(){var g=void 0,h=true,i=null,j=false,l,m=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b){function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ca(){}
function da(a,b,c){switch(typeof b){case "string":ea(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),da(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),ea(e,c),c.push(":"),da(a,f,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ga={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ha=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ea(a,b){b.push('"',a.replace(ha,function(a){if(a in ga)return ga[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return ga[a]=e+b.toString(16)}),'"')};var ia={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ja={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function ka(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function o(a,b){var c="",d=la(encodeURIComponent(a));d.splice(b||5,d.length);q(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function la(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,n=3285377520,p=[],k,u,x,J,K,fa=Math.ceil((a.length/4+2)/16),V=[fa],z=0,w;z<fa;z++){V[z]=[];for(k=0;k<16;k++)V[z][k]=a.charCodeAt(z*64+k*4)<<24|a.charCodeAt(z*64+k*4+1)<<16|a.charCodeAt(z*64+k*4+2)<<8|a.charCodeAt(z*64+k*4+3)}z=(a.length-1)*8;a=fa-1;V[a][14]=Math.floor(z/Math.pow(2,32));V[a][15]=z&4294967295;for(z=0;z<fa;z++){for(w=0;w<16;w++)p[w]=V[z][w];
for(w=16;w<80;w++)p[w]=(p[w-3]^p[w-8]^p[w-14]^p[w-16])<<1|(p[w-3]^p[w-8]^p[w-14]^p[w-16])>>>31;a=c;k=d;u=e;x=f;J=n;for(w=0;w<80;w++)K=Math.floor(w/20),K=(a<<5|a>>>27)+(K==0?k&u^~k&x:K==1?k^u^x:K==2?k&u^k&x^u&x:k^u^x)+J+b[K]+p[w]&4294967295,J=x,x=u,u=k<<30|k>>>2,k=a,a=K;c=c+a&4294967295;d=d+k&4294967295;e=e+u&4294967295;f=f+x&4294967295;n=n+J&4294967295}return[c,d,e,f,n]}
function ma(a){var b=m.navigator,c=m.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];q(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=m.performance;d=d.concat([b&&b.now?b.now():"",document.title,m.location.href,r(),ka()]);return d.concat(a||[]).join()}function s(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function t(a){return typeof a!=="undefined"}function na(a){return a.replace(/^www\./,"")}var oa=/^((https?\:)?(\/\/))/i;function pa(a){return a.replace(oa,"")}var qa=/^((https?\:)?(\/\/))?[^\/]*/;function ra(a){return a.replace(qa,"")}var sa=/\#.*/;function ta(a){return a.replace(sa,"")}var ua=/\?[^\#]*/;function va(a){return a.toLowerCase()}var wa=/\/+((\?|\#).*)?$/;function xa(a){return a.replace(wa,"$1")}function ya(a){return a.replace(ua,"")}
function za(a,b){if(a===b)return 0;var c=i;q([va,xa,pa,ra,ta,ya],function(d,e){a=d(a);b=d(b);if(a===b)return c=e+1,j});return c}function v(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function Aa(a,b){var c=m;c.removeEventListener?c.removeEventListener(a,b,j):c.detachEvent&&c.detachEvent("on"+a,b)}function y(a){return typeof a==="number"}function A(a){return typeof a==="string"}
function Ba(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function r(){return(new Date).getTime()}function Ca(){return m.location.protocol==="https:"?"https:":"http:"}function q(a,b){if((!!a&&a.constructor===Object)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}function Da(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}
function Ea(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,n=a.length;f<=n;f++)c[0][f]=f;for(var p,k,u,d=1;d<=e;d++)for(f=1;f<=n;f++)p=d-1,k=f-1,u=c[p][k],b.charAt(p)==a.charAt(k)?c[d][f]=u:(k=c[d][k]+1,p=c[p][f]+1,u+=2,c[d][f]=Math.min(k,p,u));return c[b.length][a.length]}var Fa,Ga=m.setInterval,Ha=m.clearInterval,Ia=m.setTimeout,B=m.clearTimeout;
function Ja(a){switch(a){case g:return"undefined";case "":return"empty";default:return a}};function Ka(a,b,c){c=c||"";if(a===g)a=j;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?j:Ka(a.parentNode,b,c)}return a}
function La(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c){var d,e;d=d||"*";e=e||document;if("querySelectorAll"in e)c=e.querySelectorAll(d+"[data-cb-scroll-element]");else{c=[];d=e.getElementsByTagName(d);for(e=d.length;e--;)d[e].getAttribute("data-cb-scroll-element")&&c.push(d[e])}if(c&&c.length)return c[0][b]}if(y(m[a]))return m[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}
function Ma(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function C(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}
function Na(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var d=a.ownerDocument.documentElement,e=0,f=t(c)?c+1:-1;A(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function Oa(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Pa(a){a=a||window.event;return!a?i:Na(a.target||a.srcElement,Oa,10)}function Qa(a,b){var c=document.createElement(a);q(b,function(a,b){c.setAttribute(b,a)});return c};function Ra(){this.G={};this.Ta=1}function D(a,b,c,d){a.Ta++;a.G[b]=a.G[b]||{};a.G[b][a.Ta]=[c,d];return a.Ta}function E(a,b){if(A(b))a.G[b]=g,delete a.G[b];else if(y(b)){var c=h;q(a.G,function(a){q(a,function(e,f){if(parseInt(f,10)===b)return a[f]=g,delete a[f],c=j});return c})}}Ra.prototype.O=function(a,b){if(this.G[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];q(this.G[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
Ra.prototype.addEventListener=function(a,b){var c=D(this,a,b);b._cbEventId=c};Ra.prototype.removeEventListener=function(a,b){this.G[a]&&this.G[a][b._cbEventId]&&this.G[a][b._cbEventId][0]===b&&E(this,b._cbEventId)};var F=new Ra,Sa="a";var G={};
G.B=function(){G.Fa?G.pa("pageload"):(G.ob=[{target:m,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:m,event:"resize"},{target:document.body,event:"mousedown"}],G.wa=i,G.T=i,G.Ea={},G.Da={},G.eb={},G.xa={},q(G.ob,function(a){var b=a.event;v(a.target,b,function(a){G.pa.call(G,b,a)})}),D(F,"f",function(){G.pa("focus")}),G.pa("pageload"),v(document.body,"click",function(a){(a=Pa(a))&&F.O("c",a)},h),v(document.body,"contextmenu",function(a){(a=Pa(a))&&
F.O("r",a)}),G.Fa=h)};G.vb=function(){var a,b=G.eb.keydown;if(b===g)return j;b=r()-b;return b<=(a||15E3)&&b>=0};G.fa=function(a,b){var c=G.xa[a];if(!c)return"";var b=b||r(),d,e=0;q(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(e|=1<<d)});c=("0000"+e.toString(16)).slice(-4);return c=="0000"?"":c};G.Ub=function(){G.xa={}};G.Xa=100;
G.pa=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}G.ac(a);if(G.wa===i)G.mb(a);else if(!G.T||ia[G.T]<ia[a]||ja[G.T]<ja[a])G.T=a};G.ac=function(a){var b=r();G.eb[a]=b;var c=G.xa[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();G.xa[a]=c};G.mb=function(a){G.wa=Ia(G.zb,G.Xa);F.O(Sa);G.Ea[a]!==i&&B(G.Ea[a]);G.Da[a]!==i&&B(G.Da[a]);G.lb(a,G.Ea,ia,"i");G.lb(a,G.Da,ja,"j")};
G.lb=function(a,b,c,d){b[a]=Ia(function(){B(b[a]);delete b[a];var c=j;q(b,function(){c=h;return j});c||F.O(d)},c[a]+G.Xa)};G.zb=function(){B(G.wa);G.wa=i;if(G.T)G.mb(G.T),G.T=i};var Ta,Ua,H,Va,Wa;(function(){var a,b;q(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof m.document[a]==="boolean")return b=c,j});b!==g&&(Va=a,Wa=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),H=b+"visibilitychange")})();var I=j;function Xa(){I=Wa&&m.document[Wa]==="prerender"?h:j}function Ya(){Ua=h;F.O("f")}function Za(){Ua=j;F.O("b")}
function $a(a,b,c){m.addEventListener?m.addEventListener(a,c,j):m.document.attachEvent&&m.document.attachEvent(b,c)}function ab(){var a=h;m.document.hasFocus&&(a=m.document.hasFocus());var b=j;Va&&(b=m.document[Va]);return a&&!b}function bb(){ab()?Ya():Za()}function cb(a){Xa();if(I){var b=j,c=function(){b||(Xa(),I||(b=h,a(),m.window.setTimeout(function(){m.document.removeEventListener(H,c,j)},100)))};m.document.addEventListener(H,c,j)}else a()};function L(){this.a=m._sf_async_config||{};this.Za=s(this.ib,this)}L.prototype.B=function(){this.jb=0};L.prototype.ib=function(){};L.prototype.ta=function(a){if(!I){var b=this.Za,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};L.prototype.da=function(){this.Za=i};function db(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),q(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function eb(a,b){var c="",d=m.location.href.match(/[^?]+[?]([^#]+).*/);if(d){var d=db(d[1]),e=b||a;d[e]&&(c=d[e])}return encodeURIComponent(c)}function fb(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function gb(a){var b=[];q(hb,function(c){var d=a[c];t(d)&&(Object.prototype.toString.call(d)==="[object Array]"?q(d,function(a){b.push(c+"="+a)}):d&&d.constructor===Object?q(d,function(a,c){b.push(c+"="+a)}):((d+"").length||c=="r")&&b.push(c+"="+d))});b.push("_");return b.join("&")}
function ib(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=m.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=fb(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?
"/"+a:e.substr(0,f)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(fb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function jb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function M(a,b,c){a[b]=a[b]||c}function kb(a,b){for(var c=m[a]||[];c.length;)b(c.shift());m[a]={push:b}}function lb(a){q(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=db(b.src.split("?")[1]),M(a,"uid",b.uid),M(a,"domain",b.domain),j})}function mb(a,b){return a[b]?encodeURIComponent(a[b]):""}function nb(a){var b={};q(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};var N={};N.yb=function(){try{N.create("_cb_test","1",1);var a=N.k("_cb_test");N.remove("_cb_test");return a==="1"}catch(b){return j}};N.k=function(a){a+="=";var b="";q(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
N.create=function(a,b,c){var d=m._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(r()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};N.remove=function(a){return N.k(a)?N.create(a,"",-86400):""};var O={};O.D=function(a){var b=m._sf_async_config;if(!a&&b&&b.noCookies)return i;if(O.D.Ba!==g)return O.D.Ba;var a=r()+"",c,d;try{if((d=m.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return O.D.Ba=d}catch(e){}return O.D.Ba=i};O.k=function(a){var b=O.D();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&r()>c)?(O.remove(a),""):b.getItem(a)||""};
O.create=function(a,b,c){var d=O.D();if(d){var e=new Date;e.setTime(r()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};O.remove=function(a){var b=O.D();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function ob(a){this.sa=a||"";this.Ab=O.D()!==i||N.yb();this.Sa=j;pb(this)}l=ob.prototype;l.isSupported=function(){return this.Ab};
function pb(a){if(!N.k("_cb_ls")){var b=O.D()!==i,c=N.k("_SUPERFLY_lockout");c&&q(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,h)});var d=N.k("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,h),N.remove("_chartbeat3"));b&&((b=N.k("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,h),(b=N.k("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));N.create("_cb_ls","1",34128E3)}}l.create=function(a,b,c,d){a=d?a:this.sa+a;(O.D()?O:N).create(a,b,c);O.D()&&N.create(a,b,c)};
l.update=function(a,b,c,d,e,f,n){a=d?a:this.sa+a;e=A(e)?e:"::";d=(d=this.k(a,h))?d.split(e):[];if(n&&d.length){var p=n(b),k=Da(d,function(a){return n(a)===p});k!==-1&&d.splice(k,1)}d.push(b);for(y(f)&&d.length>f&&d.splice(0,d.length-f);d.length>1&&d.join(e).length>4E3;)d.shift();this.create(a,d.join(e),c,h)};
l.k=function(a,b){var a=b?a:this.sa+a,c=(O.D()?O:N).k(a);if(!c&&O.D()&&(c=N.k(a))&&N.k("_cb_ls")){this.Sa=h;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}O.create(a,c,d)}return c};l.remove=function(a,b){a=b?a:this.sa+a;(O.D()?O:N).remove(a);O.D()&&N.remove(a)};function qb(a){var b=i;if(a&&(b=rb()))return b;var c=m.location,b=P(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function rb(){var a=i;q(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=ib(b.href),a=P(b.pathname)+b.search+b.hash,j});return a}
for(var sb={},tb=0;tb<81;tb++)sb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(tb)]=h;function ub(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return sb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function P(a){if(!A(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,ub);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function Q(a,b){var c=R();return t(b)&&!t(c[a])?b:c[a]}function R(){t(m._cb_shared)||(m._cb_shared={});return m._cb_shared};var S={rb:{IDLE:0,qb:1,pb:2,ya:3},sb:{IDLE:0,qb:1,pb:2,ya:3},H:0,J:0};S.B=function(){if(!S.Fa)D(F,Sa,S.Hb,S),D(F,"i",S.Lb,S),D(F,"f",S.Jb,S),D(F,"b",S.Ib,S),D(F,"j",S.Kb,S),S.Fa=h};S.Eb=function(){return S.H};S.Fb=function(){return S.J};S.Hb=function(){S.H===1?S.Q(3):S.H===0&&S.Q(2);S.J===1?S.P(3):S.J===0&&S.P(2)};S.Lb=function(){S.H===3?S.Q(1):S.H===2&&S.Q(0)};S.Kb=function(){S.J===3?S.P(1):S.J===2&&S.P(0)};S.Jb=function(){(S.H===0||S.H===2)&&S.Q(3);(S.J===0||S.J===2)&&S.P(3)};
S.Ib=function(){S.H===3?S.Q(2):S.H===1&&S.Q(0);S.J===3?S.P(2):S.J===1&&S.P(0)};S.Q=function(a){S.H=a;F.O("s",a)};S.P=function(a){S.J=a;F.O("x",a)};function vb(a,b){this.Ca=a||g;this.Ja=b||g;this.Z=this.N=0;this.bb=s(this.Ob,this);this.Ra=this.M=i}l=vb.prototype;l.B=function(){this.Z=this.N=0;this.M=i;this.Ra=D(F,"s",this.ga,this);this.ga(S.Eb())};l.ga=function(a){Ha(this.M);this.M=i;if(a===S.rb.ya)this.M=Ga(this.bb,1E3)};l.Ob=function(){if(this.Ca===g||this.Ca())this.N++,this.Z++,this.Ja&&this.Ja()};l.terminate=function(){Ha(this.M);this.M=i;E(F,this.Ra)};l.da=function(){this.terminate();this.Ja=this.Ca=g};function wb(a,b){vb.call(this,a,b)}ba(wb,vb);wb.prototype.B=function(){this.Z=this.N=0;this.M=i;this.Ra=D(F,"x",this.ga,this);this.ga(S.Fb())};wb.prototype.ga=function(a){Ha(this.M);this.M=i;if(a===S.sb.ya)this.M=Ga(this.bb,1E3)};function T(){L.call(this);this.X=[];this.q=new ob(this.Yb);this.q.remove("_SUPERFLY_nosample");this.F=new vb;this.U=new wb;this.Ka=s(this.ra,this);v(m,"unload",this.Ka);cb(s(this.B,this))}ba(T,L);l=T.prototype;l.Oa=h;
l.B=function(){T.S.B.call(this);this.na=this.$=0;this.ca=r();this.Na=o(xb(this));this.Ma=h;this.Ga=72E5;if(this.Oa){var a=+this.a.sessionLength;if(!isNaN(a))this.Ga=a*6E4}a=Q("d");if(!a){var a=[],b=this.q.k("_chartbeat2",h);b.length>0&&(a=b.split("."));a.length>5&&(a=[]);var b=r(),c=this.q.k("_cb",h);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var d=b-+(a[1]||0),e=b-+(a[2]||0);R().n=c&&d>18E5&&e<2592E6?0:1;d=a[4];if(!(e=e>18E5))if(yb(this))e=j;else{var e=U(this),e=decodeURIComponent(e),e=zb(e)||e,f;f=
Ab(this);f=decodeURIComponent(f);f=zb(f)||f;e=e!==f}if(!d||e)d=o(xb(this)),a[4]=d,this.q.remove("_cb_svref",h);e="1";f=a&&+a[2];d=a&&a[3];if(a&&f&&d)if(e=Math.abs((Ba(b)-Ba(f))/864E5)){e=Math.min(e,16)-1;for(f="";e--;)f+=0;e=(d+f+"1").slice(-16)}else e=d;d=e;c||(c=this.a.utoken||o(xb(this),3),a[1]=b);a[2]=b;a[3]=d;this.a.utoken=this.la;this.q.create("_cb",c,34128E3,h);this.q.create("_chartbeat2",a.join("."),34128E3,h);a[0]=c;R().d=a}this.lc=a.join(".");var n;c=+a[1];d=+a[2];if((b=a[3])&&c&&d)n=(Math.min((Math.abs((Ba(d)-
Ba(c))/864E5)||0)+1,16,b.length)-1).toString(16),n+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.ab=n;this.Qb=Q("n",1);this.la=a[0];this.Xb=a[4];this.Wb=Ab(this);this.q.create("_cb_svref",Ab(this)||"null",1800,h);this.F.B();this.U.B();S.B();G.B();Ta||(Ua=ab(),H&&m.document.addEventListener&&m.document.addEventListener(H,bb,j),$a("focus","onfocusin",Ya),$a("blur","onfocusout",Za),Ua&&Ya(),Ta=h);this.ia=0;this.ub=D(F,Sa,this.Rb,this)};
function Bb(a){if(!a.q.k("_SUPERFLY_lockout")&&!I)a.Pb?a.ua():(a.Pb=h,!m._sf_async_config&&!m._cbq?(a.qa=s(a.ua,a),v(m,"load",a.qa)):a.ua())}l.ua=function(){this.La=Cb();G.B();var a=s(this.ja,this);this.cb=Ga(a,15E3);this.ja()};
l.ja=function(){var a=this.F.Z,a=this.a.reading&&+this.a.reading||a>0;if(this.na<this.$&&!a)this.na++;else{var b;if(Fa===g)b=m.navigator.userAgent,Fa=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Fa;b&&!a?this.na++:(a?this.$=0:Db(this),this.na=0,this.X.push(0),this.X.length>18&&this.X.shift(),this.Oa&&r()-this.ca>=this.Ga?this.terminate():this.ka())}};
l.ib=function(){this.X.push(1);var a=0;q(this.X,function(b){a+=b});a<3?(this.Ma=h,Db(this)):(this.terminate(),this.q.create("_SUPERFLY_lockout","1",600))};l.ra=function(){};l.Rb=function(){var a=Eb(this);this.ia=Math.max(this.ia,a)};function Eb(a){return Math.floor(La("Y","Top",!!a.a.scrollElement))}function Db(a){var b=a.$,b=b?Math.min(b*2,16):1;a.$=b}l.ma=function(){this.ra();this.terminate()};l.nb=function(){this.B();Bb(this)};
function yb(a){if(a.a.virtualReferrer)return h;if(Fb(a))return j;a=document.referrer.indexOf("://"+m.location.hostname+"/");return a!=-1&&a<9}function Fb(a){var b=a.a.referrerOverrideQueryParam,c="";q(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),j});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function U(a){a=a.a.virtualReferrer||Fb(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=ib(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=P(b.pathname),a=jb(b)}return encodeURIComponent(a)}function Gb(a){a=a.a.title.slice(0,100);return encodeURIComponent(a)}function xb(a){a=[U(a),C("Width"),C("Height")];return ma(a)}
function Hb(a){var b=[],c=a.q.k("_chartbeat4");c&&(q(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.q.remove("_chartbeat4"));return b}function Ab(a){a=a.q.k("_cb_svref",h)||U(a)||"null";a==="null"&&(a="");return a}function zb(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?i:a[1]}function Cb(){var a=m.performance&&m.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return y(b)&&b?y(a)&&a>b?a-b:r()-b:-1}
l.terminate=function(){this.F.terminate();this.U.terminate();E(F,this.ub);this.qa!==g&&Aa("load",this.qa);Ha(this.cb);R().d=g;R().n=g};l.da=function(){this.terminate();Aa("unload",this.Ka);this.Ka=this.qa=this.q=this.X=this.a=i;this.F.da();this.F=i;this.U.da();this.U=i;T.S.da.call(this)};function Ib(a){for(var b=Q("m")||[];b.length;)a(b.shift());a={push:a};R().m=a};function Jb(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=Kb(a);d+=f.x;e+=f.y;for(var n=j,p=c?0:Math.floor(La("X","Left",g)),k=c?0:Math.floor(La("Y","Top",g)),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=Kb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(Lb(a,["position"]).position==="fixed"){n=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:p,e-=b?b.scrollTop:k);n&&(d+=p,e+=k);return{x:d,y:e}}
function Lb(a,b){var c={},d,e;m.getComputedStyle?d=m.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");q(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var Mb=/matrix(3d)?\((.*)\)/;function Kb(a){var b={x:0,y:0},a=Lb(a,["transform"]).transform;if(!A(a))return b;var c=a.match(Mb);if(!c)return b;var a=c[2].split(", "),d;t(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};function Nb(){var a=m.location.href,a=a.replace(/-{2,}/g,"-"),a=ib(a);a.pathname=P(a.pathname);return a}
function Ob(a){var b=N.k("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=Nb(),n=jb(f);q(b,function(a,b){var f=a.split(","),k=Ea(n,decodeURIComponent(f[0]));if(k===0)return c=f,d=b,j;if(e===g||k<e)e=k,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+Pb(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),f=decodeURIComponent(c[1]),p=c[2];c.splice(0,3);for(var k=c.length/3,u=0;u<k;u++){var x=u*3+2;a.push({jc:b,origin:f,aa:p,ba:x<c.length?
c[x]:"",Bb:c[u*3],bc:c[u*3+1]})}return a}function Pb(a){var b="",c;if(!(a&&a.constructor===Object))return b;a.gb&&(c=new Date,c.setTime(c.getTime()+a.gb),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function Qb(a){var b=a.topStorageDomain,a=a.domain,c=m.location.hostname;return b?b:Rb(c,a)?a:c.replace(/^www\./,"")}
function Rb(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return h}function Sb(a,b,c,d,e){this.Db=a;this.Cb=b;this.cc=c;this.aa=d;this.ba=e}function Tb(a){var b=a.d,c=i;if(b!==i){var d={};b.s&&q(b.s,function(a,b){d[b]=typeof a==="string"?{Ya:a,ba:""}:{Ya:a.chosenVariant,ba:a.specificLocation}});c={Pa:d,aa:b.g,fb:b.m}}return{status:a.s,data:c,code:a.c,message:a.m}};function Ub(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,n,p,k,u,x,J;f&&f!==c;){n=f.nodeName.toLowerCase();e=f;p=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){k=f.children;u=0;for(x=0,J=k.length;x<J;x++){if(e===k[x]){n+="["+(1+x-u)+"]";break}k[x].nodeName!==p&&u++}}d.unshift(n)}return d.join("/")};function W(){this.Yb="_t_";T.call(this)}ba(W,T);l=W.prototype;
l.B=function(){W.S.B.call(this);lb(this.a);var a=m.location;M(this.a,"mabServer","mabping.chartbeat.net");M(this.a,"title",document.title);M(this.a,"domain",a.hostname);M(this.a,"path",qb(!!this.a.useCanonical));this.ha=na(a.hostname);this.a.domain=na(this.a.domain);this.$b=Qb(this.a);this.ea=this.oa=j;this.$a=[];var b=this,a=Ob({domain:"."+this.$b,gb:6E4,path:"/"});if(a!==i)this.oa=h,q(a,function(a){b.$a.push(new Sb(a.origin,a.Bb,a.bc,a.aa,a.ba))});this.hb=0;this.va=i;Ib(s(this.Nb,this))};
l.ka=function(){var a=this.F.N,b=Vb(this),c,d=this;this.oa&&q(this.$a,function(e){c=b+"&x="+e.Cb+"&v="+e.cc+"&ml="+e.aa+"&xo="+e.Db+"&e="+a+"&sl="+e.ba;d.ta(c)});!this.ea&&this.va&&Wb(this,this.va);this.ea=h};l.ua=function(){this.La=Cb();G.B();if(this.oa){var a=s(this.ja,this);this.cb=Ga(a,500)}this.ja()};l.ja=function(){var a,b;this.ea?(a=this.F.N,b=this.hb*15,a-b>=15&&(this.ka(),this.hb+=1),a>=45&&this.terminate()):this.ka()};
function Vb(a){var b=a.a;return Ca()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ha)+"&u="+a.la+"&c="+Math.round((r()-a.ca)/600)/100}l.ra=function(){};l.Zb=function(a){a=Tb(a);this.ea?Wb(this,a):this.va=a};
function Wb(a,b){var c=Vb(a),d=b.status,e=b.data;if(d=="s"&&e!==i){var f=s(a.ta,a);e.Pa&&e.Pa.constructor===Object&&q(e.Pa,function(a,b){f(c+"&x="+b+"&v="+a.Ya+"&ml="+e.aa+"&sl="+a.ba+"&e=-1")});Object.prototype.toString.call(e.fb)==="[object Array]"&&q(e.fb,function(a){f(c+"&me=3&ml="+e.aa+"&x="+a)})}else d=="e"&&a.ta(c+"&me="+b.code)}l.Nb=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.Zb.apply(this,a):e==="v"&&this.Vb.apply(this,a)}};
l.ma=function(){R().m=[];t(this.Ua)&&this.Ua();W.S.ma.call(this)};l.Vb=function(a){this.Ua=a};l.terminate=function(){this.Ua=this.kc=g;this.va=i;this.ea=this.oa=g;W.S.terminate.call(this)};if(!m.pSUPERFLY_mab){var Xb=new W,Yb={};Yb.evps=s(Xb.ma,Xb);Yb.svps=s(Xb.nb,Xb);m.pSUPERFLY_mab=Yb;Bb(Xb)};var Zb="engagedSeconds",$b={hc:"id",gc:Zb,dc:"campaignId",ec:"creativeId",ic:"placementId",fc:"element"};var ac,bc,X;
function cc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);dc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=t(g)?g:{},b.src=a,a=Qa("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],t(g)?g.appendChild(a):b&&b.appendChild(a)}}
function dc(){B(bc);bc=g;Aa("message",cc);X&&X.parentNode&&X.parentNode.removeChild(X);X=g};function ec(){var a=m._sf_async_config&&m._sf_async_config.domain;if(a&&!ac){ac=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);v(m,"message",cc);bc=Ia(dc,1E4);var b=t(g)?g:{};b.src=a;a=Qa("iframe",b);a.style.display="none";t(g)?g.appendChild(a):document.body&&document.body.appendChild(a);X=a}}
function fc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=O.D(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),ec(),Aa("message",fc))}};function Y(){"postMessage"in window&&v(m,"message",s(this.Mb,this));T.call(this);kb("_cbq",s(this.kb,this))}ba(Y,T);
Y.prototype.B=function(){Y.S.B.call(this);var a=this.la;R().u=a;a=this.Na;R().t=a;this.Aa=i;lb(this.a);a=m.location;M(this.a,"pingServer","ping.chartbeat.net");M(this.a,"title",document.title);M(this.a,"domain",a.hostname);this.a.path=this.a.path?P(this.a.path):qb(!!this.a.useCanonical);this.ha=na(a.hostname);this.a.domain=na(this.a.domain);this.wb=D(F,"c",this.Sb,this);this.xb=D(F,"r",this.Tb,this);this.Y=i};Y.prototype.tb=function(a){this.Aa=a};
Y.prototype.ra=function(){this.q.update("_chartbeat4",["t="+this.Na,"E="+this.F.N,"EE="+this.U.N,"x="+Eb(this),"c="+Math.round((r()-this.ca)/600)/100,"y="+C("Height"),"w="+Ma("Height")].join("&"),60,g,g,1)};var hb="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE,sv,sr".split(",");l=Y.prototype;
l.ka=function(a){this.jb++;var b={};b.g=this.a.uid;b.g0=mb(this.a,"sections");b.g1=mb(this.a,"authors");b.g2=mb(this.a,"zone");b.g3=mb(this.a,"sponsorName");b.g4=mb(this.a,"type");!this.a.noCookies&&this.q.isSupported()?b.n=this.Qb:b.nc=1;b.c=Math.round((r()-this.ca)/600)/100;b.E=this.F.N;b.EE=this.U.N;var c=Eb(this);this.ia=Math.max(this.ia,c);b.x=c;b.m=this.ia;b.y=C("Height");b.o=C("Width");b.w=Ma("Height");b.b=this.La>0?this.La:"";if(this.ab)b.f=this.ab;b[""]=nb(this.a);b.t=this.Na;b.V=95;b.tz=
(new Date).getTimezoneOffset();b.sn=this.jb;b.sv=this.Xb;b.sr=this.Wb;c=this.F.Z;b.h=encodeURIComponent(this.a.domain);b.p=encodeURIComponent(this.a.path);b.u=this.la;b.d=encodeURIComponent(this.ha);b.j=Math.round((this.$+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.ca;b.eD=G.fa("mousedown",d);b.eM=G.fa("mousemove",d);b.eK=G.fa("keydown",d);b.eR=G.fa("resize",d);b.eS=G.fa("scroll",d);G.Ub();G.vb()?b.W=1:this.a.reading&&+this.a.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=yb(this);if(this.Ma){this.Ma=
j;if(c)this.Y=gc(this);b.i=Gb(this);d=this.a.hudTrackable;d!==g&&(b.L=d?"1":"0");this.a.alias&&(b.PA=encodeURIComponent(this.a.alias))}if(c){if(this.Y){if(b.v=encodeURIComponent(this.Y.path),b.K=hc(this.Y),this.Y.Ia>1)b.l1=this.Y.Ia}else b.v=U(this);this.a.virtualReferrer&&(b.vp=1)}else b.r=U(this);c=Ja(b.v);R().v=c;c=Ja(b.r);R().r=c;b.A=this.Aa?this.Aa:"";b._c=eb("utm_campaign",this.a.campaignTag);b._m=eb("utm_medium",this.a.mediumTag);b._x=eb("utm_source",this.a.sourceTag);b._y=eb("utm_content",
this.a.contentTag);b._z=eb("utm_term",this.a.termTag);this.a.idSync?(c=[],da(new ca,this.a.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=Hb(this);b.C=this.a.mobileApp?1:"";b.KK=a?hc(a):"";a=this.q;c=a.Sa;a.Sa=j;b.l=c?1:"";this.F.Z=0;this.ta(Ca()+"//"+this.a.pingServer+"/ping?"+gb(b))};
l.Mb=function(a){var b=this.a,c=b.playerdomain||this.ha;if(pa(a.origin)===pa(c))if(c=a.data,A(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.kb(a));else if(c=="cbdata?"){var c="&u="+Q("u"),d="&t="+Q("t"),e="&v="+Q("v"),f="&r="+Q("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+Gb(this)+"&referrer="+U(this)+"&internal="+(yb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ha)+
c+d+e+f+"&utoken="+this.la;a.source.postMessage(b,"*")}};l.kb=function(a){a[0]==="_demo"&&this.a._demo?this.a._demo=this.a._demo+"%2C"+a[1]:this.a[a[0]]=a[1];this.$=0};function ic(a){a=a.replace(/-{2,}/g,"-");a=ib(a);a.pathname=P(a.pathname);return a}l.Sb=function(a){jc(this,a,"c")};l.Tb=function(a){jc(this,a,"r")};
function jc(a,b,c){if(a.Oa&&r()-a.ca>=a.Ga)a.terminate();else{var d=b.href||"",d=ic(d);if(d.protocol.indexOf("http")===0){var e=d.hostname!==m.location.hostname,d=jb(d),f=Na(b,function(a){return a.id}),n=Ub(b,f),p="";a.a.moduleAttribute&&(p=(p=Ka(b,a.a.moduleAttribute))?p.getAttribute(a.a.moduleAttribute):"",p=p.replace(/::/g,"-").substr(0,40));f?(n&&(n="/"+n),n="*[@id='"+f.id+"']"+n,f=Ub(b)):f=n;n=o(n);f=o(f);b=Jb(b,g,h);c={left:b.x,top:b.y,path:a.a.path,href:d,Wa:n,za:f,Va:"",Qa:c,Ia:0,Gb:a.a.domain,
Ha:p};a.ka(c);e||a.q.update("_chartbeat5",kc(c),60,j,g,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function hc(a){return[a.left,a.top,a.Wa,encodeURIComponent(a.Va),a.Qa,encodeURIComponent(a.href),a.za,a.Ha].join("::")}function kc(a){var b=encodeURIComponent(a.Va),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Wa,b,a.Qa,a.za,encodeURIComponent(a.Gb),a.Ha].join(",")}
function gc(a){var b=a.q.k("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,e=i,f,n=ic(m.location.href),p=jb(n);q(c,function(a,b){var c=a.split(","),n=za(p,decodeURIComponent(c[3]));if(n===0)return d=c,e=b,j;else if(n===i)return h;if(f===g||n<f)f=n,d=c,e=b});if(e===i)return i;c.splice(e,1);a.q.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),Wa:d[4]||
"",Va:"",za:d.length>7?d[7]:"",Qa:d.length>6?d[6]:"c",Ia:b,Ha:d[9]?d[9]:""}}l.terminate=function(){E(F,this.wb);E(F,this.xb);Y.S.terminate.call(this)};if(!m.pSUPERFLY){var lc=new Y,Z={};m.pSUPERFLY=Z;var mc=m.pSUPERFLY_mab,$=m.pSUPERFLY_pub,nc=[];mc&&nc.push(mc);if($)nc.push($),$.addEngagedAdFilter&&(Z.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(Z.refreshAd=$.refreshAd),$.registerGptSlot&&(Z.registerGptSlot=$.registerGptSlot),kb("_cba",function(a){a()});Z.virtualPage=function(a,b){if(!I){var c=m._sf_async_config;c.virtualReferrer=Ca()+"//"+c.domain+c.path;c.path=P(a);b&&(c.title=b);lc.ma();q(nc,function(a){a.evps()});lc.nb();q(nc,function(a){a.svps()})}};
Z.activity=s(lc.tb,lc);Bb(lc);var oc=O.D(h);if(oc)if(oc.getItem("_cb_ip")){var pc=m.location;(!/^(.+[.])?chartbeat\.com$/.test(pc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(pc.pathname))||ec()}else v(m,"message",fc)};})();
